# Generated by Django 3.2.9 on 2021-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0008_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='custom data'),
        ),
        migrations.AlterField(
            model_name='space',
            name='custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='custom data'),
        ),
        migrations.AlterField(
            model_name='spaceresource',
            name='custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='custom data'),
        ),
    ]
