# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='created at')),
                ('type', models.CharField(choices=[('link', 'link'), ('status', 'status'), ('photo', 'photo'), ('video', 'video'), ('event', 'event')], max_length=30, verbose_name='type')),
                ('source_type', models.CharField(choices=[(('FACEBOOK',), 'Facebook'), ('TWITTER', 'Twitter')], max_length=30, verbose_name='source')),
                ('source_id', models.CharField(blank=True, max_length=60, verbose_name='source id')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('link', models.URLField(blank=True, verbose_name='link')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(blank=True, verbose_name='src')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('title', models.TextField(blank=True, max_length=200, verbose_name='title')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fablabsch.Post', verbose_name='post')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='name')),
                ('type', models.CharField(max_length=30, verbose_name='name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture')),
                ('custom_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='custom data')),
            ],
            options={
                'ordering': ('vendor__name', 'model'),
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(default='CH', max_length=2, verbose_name='name')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='state')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='street')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='zip')),
                ('founded', models.DateField(blank=True, null=True, verbose_name='founded')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='twitter')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='', verbose_name='background')),
                ('type', models.CharField(default='FabLab', max_length=20, verbose_name='type')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='language')),
                ('last_confirmed', models.DateField(blank=True, null=True, verbose_name='last confirmed')),
                ('custom_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='custom data')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpaceResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='custom data')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablabsch.Resource', verbose_name='resource')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablabsch.Space', verbose_name='space')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='space',
            name='resources',
            field=models.ManyToManyField(blank=True, through='fablabsch.SpaceResource', to='fablabsch.Resource', verbose_name='resources'),
        ),
        migrations.AddField(
            model_name='resource',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='fablabsch.Vendor', verbose_name='vendor'),
        ),
        migrations.AddField(
            model_name='post',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='fablabsch.Space', verbose_name='space'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('source_type', 'source_id')]),
        ),
    ]
