# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='resources',
        ),
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.BooleanField(default=False, verbose_name='show'),
        ),
        migrations.AddField(
            model_name='space',
            name='show',
            field=models.BooleanField(default=False, verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='model',
            field=models.CharField(max_length=30, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='spaceresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='fablabsch.Resource', verbose_name='resource'),
        ),
        migrations.AlterField(
            model_name='spaceresource',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='fablabsch.Space', verbose_name='space'),
        ),
    ]
