# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0002_auto_20160224_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='marker',
            field=models.ImageField(blank=True, null=True, upload_to='marker', verbose_name='marker'),
        ),
    ]
