# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0002_auto_20160221_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show',
            field=models.BooleanField(default=True, verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resource', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='space',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background', verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='space',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor', verbose_name='logo'),
        ),
    ]
