# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0003_auto_20160221_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 2, 21, 12, 32, 17, 100960, tzinfo=utc), verbose_name='slug'),
            preserve_default=False,
        ),
    ]
