# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0003_space_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='facebook',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='space',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='space',
            name='twitter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='twitter'),
        ),
    ]
