# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabsch', '0006_space_events_ics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
        ),
    ]
